noLocale:
  path: /
  controller: App\Controller\DefaultController::defaultLocaleAction

app:
  prefix: /{_locale}/
  type: annotation
  resource: ../src/Controller/*
  requirements:
    _locale: en|ru|uk|fr|de

logout:
  path: /logout
  methods: GET